on: pull_request
name: Triage Pull Request
jobs:
  mainJob:
    name: Triage
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Analyze and triage
      uses: ohmyzsh/github-actions/pull-request-triage@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
